Repository salesforce/lwc, pull requests merged in 2024-12, with the labels that each got.

#4975 fix(ssr): correct import alias for generateMarkup symbol in lwc-component
  packages/@lwc/ssr-compiler/src/__tests__/utils/expected-failures.ts
  packages/@lwc/ssr-compiler/src/compile-template/transformers/component/lwc-component.ts
Labels: cla:signed

#4976 fix(template-compiler): dynamic components with scoped slots
  packages/@lwc/engine-server/src/__tests__/fixtures/dynamic-components/slots/scoped-slots/config.json
  packages/@lwc/engine-server/src/__tests__/fixtures/dynamic-components/slots/scoped-slots/error-ssr.txt
  packages/@lwc/engine-server/src/__tests__/fixtures/dynamic-components/slots/scoped-slots/error.txt
  packages/@lwc/engine-server/src/__tests__/fixtures/dynamic-components/slots/scoped-slots/expected-ssr.html
  packages/@lwc/engine-server/src/__tests__/fixtures/dynamic-components/slots/scoped-slots/expected.html
  packages/@lwc/engine-server/src/__tests__/fixtures/dynamic-components/slots/scoped-slots/modules/x/test/test.js
  packages/@lwc/template-compiler/src/parser/index.ts
Labels: cla:signed

#5001 chore: use eslint cache
  .gitignore
  package.json
Labels: cla:signed

#5024 chore: test usage of default slot with scoped data
  packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/default-slot/error.txt
  packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/default-slot/expected.html
  packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/default-slot/index.js
  packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/default-slot/modules/x/child/child.html
  packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/default-slot/modules/x/child/child.js
  packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/default-slot/modules/x/parent/parent.html
  packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/default-slot/modules/x/parent/parent.js
  packages/@lwc/ssr-compiler/src/__tests__/utils/expected-failures.ts
Labels: tests

#5005 fix(ssr): extra bookends for light dom forwarded slots @W-17363666
  packages/@lwc/engine-server/src/__tests__/fixtures/slotted-content-nested/error.txt
  packages/@lwc/engine-server/src/__tests__/fixtures/slotted-content-nested/expected.html
  packages/@lwc/engine-server/src/__tests__/fixtures/slotted-content-nested/index.js
  packages/@lwc/engine-server/src/__tests__/fixtures/slotted-content-nested/modules/x/another/another.html
  packages/@lwc/engine-server/src/__tests__/fixtures/slotted-content-nested/modules/x/another/another.js
  packages/@lwc/engine-server/src/__tests__/fixtures/slotted-content-nested/modules/x/receiver/receiver.html
  packages/@lwc/engine-server/src/__tests__/fixtures/slotted-content-nested/modules/x/receiver/receiver.js
  packages/@lwc/engine-server/src/__tests__/fixtures/slotted-content-nested/modules/x/slots/slots.html
  packages/@lwc/engine-server/src/__tests__/fixtures/slotted-content-nested/modules/x/slots/slots.js
  packages/@lwc/ssr-compiler/src/__tests__/utils/expected-failures.ts
  packages/@lwc/ssr-compiler/src/compile-template/transformers/component/slotted-content.ts
  packages/@lwc/ssr-compiler/src/compile-template/transformers/if.ts
  packages/@lwc/ssr-compiler/src/compile-template/transformers/slot.ts
  packages/@lwc/ssr-compiler/src/compile-template/types.ts
Labels: cla:signed

#5038 always use / when splitting filename to get name and namespace
  packages/@lwc/rollup-plugin/src/index.ts
Labels: cla:signed

#5034 fix: replace barrel exports from `lwc` with `@lwc/ssr-runtime`
  packages/@lwc/engine-server/src/__tests__/fixtures/barrel-lwc-exports/export-all-alias/barrel.js
  packages/@lwc/engine-server/src/__tests__/fixtures/barrel-lwc-exports/export-all-alias/error.txt
  packages/@lwc/engine-server/src/__tests__/fixtures/barrel-lwc-exports/export-all-alias/expected.html
  packages/@lwc/engine-server/src/__tests__/fixtures/barrel-lwc-exports/export-all-alias/index.js
  packages/@lwc/engine-server/src/__tests__/fixtures/barrel-lwc-exports/export-all-alias/modules/x/cmp/cmp.html
  packages/@lwc/engine-server/src/__tests__/fixtures/barrel-lwc-exports/export-all-alias/modules/x/cmp/cmp.js
  packages/@lwc/engine-server/src/__tests__/fixtures/barrel-lwc-exports/export-all/barrel.js
  packages/@lwc/engine-server/src/__tests__/fixtures/barrel-lwc-exports/export-all/error.txt
  packages/@lwc/engine-server/src/__tests__/fixtures/barrel-lwc-exports/export-all/expected.html
  packages/@lwc/engine-server/src/__tests__/fixtures/barrel-lwc-exports/export-all/index.js
  packages/@lwc/engine-server/src/__tests__/fixtures/barrel-lwc-exports/export-all/modules/x/cmp/cmp.html
  packages/@lwc/engine-server/src/__tests__/fixtures/barrel-lwc-exports/export-all/modules/x/cmp/cmp.js
  packages/@lwc/engine-server/src/__tests__/fixtures/barrel-lwc-exports/export-named/barrel.js
  packages/@lwc/engine-server/src/__tests__/fixtures/barrel-lwc-exports/export-named/error.txt
  packages/@lwc/engine-server/src/__tests__/fixtures/barrel-lwc-exports/export-named/expected.html
  packages/@lwc/engine-server/src/__tests__/fixtures/barrel-lwc-exports/export-named/index.js
  packages/@lwc/engine-server/src/__tests__/fixtures/barrel-lwc-exports/export-named/modules/x/cmp/cmp.html
  packages/@lwc/engine-server/src/__tests__/fixtures/barrel-lwc-exports/export-named/modules/x/cmp/cmp.js
  packages/@lwc/ssr-compiler/src/compile-js/index.ts
  packages/@lwc/ssr-compiler/src/compile-js/lwc-import.ts
Labels: SSR

#5027 fix(ssr): missing bookends for slotted lwc:if not at the top-level
  packages/@lwc/ssr-compiler/src/__tests__/utils/expected-failures.ts
  packages/@lwc/ssr-compiler/src/compile-template/ir-to-es.ts
  packages/@lwc/ssr-compiler/src/compile-template/transformers/component/slotted-content.ts
Labels: cla:signed

#5058 fix(ssr-compiler): namespace & name are optional in CompilerTransformOptions
  packages/@lwc/ssr-compiler/src/__tests__/estemplate.spec.ts
  packages/@lwc/ssr-compiler/src/shared.ts
Labels: cla:signed

#5062 fix(ssr-compiler): harmonize some wire errors
  packages/@lwc/errors/src/compiler/error-info/lwc-class.ts
  packages/@lwc/ssr-compiler/src/__tests__/utils/expected-failures.ts
  packages/@lwc/ssr-compiler/src/compile-js/errors.ts
  packages/@lwc/ssr-compiler/src/compile-js/index.ts
  packages/@lwc/ssr-compiler/src/compile-js/wire.ts
Labels: cla:signed

#5063 fix(ssr): render from superclass
  packages/@lwc/ssr-compiler/src/__tests__/utils/expected-failures.ts
  packages/@lwc/ssr-compiler/src/compile-js/generate-markup.ts
  packages/@lwc/ssr-compiler/src/compile-js/index.ts
  packages/@lwc/ssr-compiler/src/compile-js/types.ts
  packages/@lwc/ssr-compiler/src/estree/validators.ts
Labels: cla:signed
